
#
# Given a set of family directories, and the corresponding kmer data directory,
# compute a merge of the families.
#
# We merge based on function. We assign function numbers based on the function.index
# file in the kmer data directory.
#
# We utilize the per-function (function index from associated kmers) fasta files of
# protein sequences as generated by pf-compute-local-families.
#
# The ids given to the proteins in the fasta files are of the form
# genus-name:genus-id:fam-id:peg so that join decisions later on can be made strictly on
# the results from the clustering on these fasta files.
#
# We use the representatives as computed by the local family code.
#
# Given the set of fasta files, we use the kmer distance clustering algorithm to
# compute suggested family merges.
#

use DBI;
use strict;
use Cwd qw(abs_path);
use Data::Dumper;
use Getopt::Long::Descriptive;
use IO::Handle;
use JSON::XS;
use File::Path 'make_path';
use File::Copy;
use File::Slurp;
use Statistics::Descriptive;
use File::Basename;
use gjoseqlib;
use Algorithm::Numerical::Shuffle qw /shuffle/;
use POSIX ':sys_wait_h';
use IPC::Run;
use LPTScheduler;
use List::Util qw(max min reduce);
use Time::HiRes qw(gettimeofday);

my($opt, $usage) = describe_options("%c %o kmer-dir merge-dir [famdir ...]",
				    ["save-work=s", "Instead of running the compute, save the work to the given file"],
				    ["family-dir-base=s", "If set, prepend this to the files in --family-dir-file"],
				    ["family-dir-file=s", "Read this file to get the list of family directories"],
				    ['inflation|I=s', 'Run MCL with this inflation parameter', { default => 2.0 } ],
				    ['subsystem=s@', "Merge roles that occur in this subsystem only", { default => [] }],
				    ["parallel|p=i", "Number of jobs to run in parallel", { default => 1 }],
				    ["kmer-parallel=i", "Number of threads to assign to kmer processing", { default => 1 }],
				    ["serial", "Force serial execution"],
				    ["log|l=s", "Trace logfile"],
				    ["dist-dir=s", "Directory into which distances are written"],
				    ["help|h", "Show this help message"]);

print($usage->text), exit if $opt->help;
die($usage->text) if @ARGV < 2;

if ($opt->log)
{
    open(LOG, ">>", $opt->log) or die "Cannot open logfile " . $opt->log . ": $!";
    LOG->autoflush(1);
}
else
{
    open(LOG, ">", "/dev/null");
}

my $kmer_dir = shift;
my $merge_dir = shift;

my @fam_dirs;

if ($opt->family_dir_file)
{
    @fam_dirs = read_file($opt->family_dir_file);
    chomp @fam_dirs;
    if ($opt->family_dir_base)
    {
	my $base = $opt->family_dir_base;
	s,^,$base/,g foreach @fam_dirs;
    }
}
else
{
    @fam_dirs = @ARGV;
}

for my $dir (@fam_dirs)
{
    if (! -d $dir)
    {
	die "Family directory $dir does not exist\n";
    }
    if (! -d "$dir/fasta_by_function")
    {
	die "Family directory $dir is missing fasta_by_function\n";
    }
}

my %desired_roles;
my($function_to_index, $index_to_function) = read_function_index($kmer_dir);

for my $subsystem (@{$opt->subsystem})
{
    my $ss_dir = "/vol/core-seed/FIGdisk/FIG/Data/Subsystems/$subsystem";
    open(S, "<",  "$ss_dir/spreadsheet") or die "Cannot open subsystem spreadsheet $ss_dir/spreadsheet: $!";
    
    while (<S>)
    {
	chomp;
	last if m,^//,;
	my($abbr, $role) = split(/\t/);
	$desired_roles{$role} = $abbr;
	if (!defined($function_to_index->{$role}))
	{
	    warn "Role $role not present in function index\n";
	}
	
    }
    close(S);
}

my $tmpdir = "$merge_dir/tmp";
make_path($tmpdir);

#remove? my $fa_dir = "$merge_dir/family.fasta";

my $dist_dir = $opt->dist_dir;
if (!$dist_dir)
{
    $dist_dir = "$merge_dir/family.dist";
}

make_path($dist_dir);

# remove? my $map_file = "$merge_dir/peg.map";

#
# Given the set of fasta data we've collected, feed the LPT scheduler
# with the functions weighted by the size of the function fasta file in a large genus.
#
# Use the size of the local.family.members file as a proxy for size, and pull per-function
# fasta sizes from there. If a function is missing, assign weight of 1000.
#

my(%fn_size, %fn_list);
for my $fd (@fam_dirs)
{
    opendir(D, "$fd/fasta_by_function") or die "Cannot opendir $fd/fasta_by_function: $!";
    for my $fn (readdir(D))
    {
	next unless $fn =~ /^\d+$/;
	my $fnfile = "$fd/fasta_by_function/$fn";
	
	$fn_size{$fn} += -s $fnfile;
	push(@{$fn_list{$fn}}, $fnfile);
    }
    closedir(D);
}

my $sched = LPTScheduler->new($opt->parallel);

$sched->add_work([$_, $fn_list{$_}], $fn_size{$_}) foreach keys %fn_size;

if ($opt->save_work)
{
    my @bins = $sched->compute_order();
    my $dat = {
	bins => \@bins,
	dist_dir => abs_path($dist_dir),
	kmer_dir => abs_path($kmer_dir),
	merge_dir => abs_path($merge_dir),
	inflation => $opt->inflation,
    };
    open(F, ">", $opt->save_work) or die "Cannot write " . $opt->save_work . ": $!";
    print F JSON::XS->new->pretty->canonical->encode($dat);
    close(F);
    exit 0;
}

$sched->run(sub {}, \&do_work);

sub do_work
{
    my($glob, $item) = @_;
    my($fn, $fa_list) = @$item;
    print "$$ $fn: @$fa_list\n";

    my $t1 = gettimeofday;

    my @cmd = ("kmers-matrix-distance-files",
	       "--n-threads", $opt->kmer_parallel,
	       "--min-kmers-in-common", 5,
	       $kmer_dir,
	       "$dist_dir/$fn",
	       @$fa_list);
    print STDERR "Run @cmd\n";
    my $rc = system(@cmd);

    my $t2 = gettimeofday;
    my $elap = $t2 - $t1;
    my $sz = 0;
    $sz += -s $_ foreach @$fa_list;
    print join("\t", "ITEM", $fn, $sz, $elap), "\n";

    if ($rc != 0)
    {
	die "Failure $rc running @cmd\n";
    }
}

sub read_function_index
{
    my($dir) = @_;

    my $idx = {};
    my $from_id = [];

    open(F, "<", "$dir/function.index") or die "Cannot open $dir/function.index:$ !";
    while (<F>)
    {
	chomp;
	my($i, $fun) = split(/\t/);
	$idx->{$fun} = $i;
	$from_id->[$i] = $fun;
    }
    close(F);
    
    return($idx, $from_id);
}






